### ISSUE TITLE
Node-gyp failures in sfacts/lowdown dependency in Node 4+

### ISSUE THREAD

**Issue by johnmenick** [superscriptjs/superscript#195]
Posted this to [sfacts repo](https://github.com/silentrob/sfacts/issues/2) but there doesn't seem to be much activity over there.

Installing on Mac OS 10.11 with Node 4.1.2 and npm 2.14.4 fails due to an outdated dependency (leveldown) in sfacts. This, in turn, is referencing an old node-gyp, which does not work with node 4.1.2. (Or at least my 4.1.2).

The leveldown dependency in sfacts is at ^0.10.2, meaning it will install 0.10.5. The latest leveldown is 1.4.2. The latest works fine for me, as does latest node-gyp. 

Is anyone else experiencing this problem?

Sorry for the cross-posting, but didn't seem like the other issue was going to be addressed via the sfacts repo. 

```
...
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/batch.cc:1:
In file included from /Users/me/.node-gyp/4.1.2/include/node/node.h:42:
/Users/me/.node-gyp/4.1.2/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/me/.node-gyp/4.1.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
9 errors generated.

...
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/nvm/0.25.4/versions/node/v4.1.2/bin/node" "/usr/local/opt/nvm/versions/node/v4.1.2/bin/npm" "i" "sfacts" "--save"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.10.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@0.10.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.
```

**Comment by dcsan** [comment]
I also had this problem trying an install 

tried with node 4.0 and 5.3 and 5.5

```
../src/node-lemmer.cc:60:11: error: member initializer 'ObjectWrap' does not name a non-static data member or base class
        : ObjectWrap()
          ^~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_lemmer/src/node-lemmer.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dc/dev/rnd/superscript/node_modules/node-lemmer
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-lemmer@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-lemmer@0.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-lemmer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-lemmer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dc/dev/rnd/superscript/npm-debug.log
```

and 5.5 (current latest)

```

npm WARN EPACKAGEJSON superscript@0.1.9 No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! node-lemmer@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-lemmer@0.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-lemmer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-lemmer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dc/dev/rnd/superscript/npm-debug.log
➜  superscript git:(master) 
```

**Comment by silentrob** [comment]
I am working on Node5 support and I did get it working.. but it is not public yet. SuperScript works today on node 0.12.x with no issues.

**Comment by aendrew** [comment]
Any update on this? I'm wanting to use Superscript with a new project I'm working, but because I'm using Koa2 and Axios (i.e., ES6-land NodeJS tools needing Node>=5.x) I currently cannot. :sob:

**Comment by silentrob** [comment]
Mater works with Node 5+ < Node 6.

**Comment by benhjames** [comment]
Travis is telling me that we're good in the latest Node 4.x, 5.x and 6.x, so hopefully this is not an issue anymore (or at least for v1)!
